// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI8j_7H9VoIFMCwGdJzEij406ap_tRlcA',
    appId: '1:478022847809:web:a75dfa45ddb28d043565c0',
    messagingSenderId: '478022847809',
    projectId: 'qrparty-6e648',
    authDomain: 'qrparty-6e648.firebaseapp.com',
    storageBucket: 'qrparty-6e648.firebasestorage.app',
    measurementId: 'G-S933V4KWMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP3VEw0T_wnaBVOG3WR3miBRIliVNPp_4',
    appId: '1:478022847809:android:7985d47a585d10cc3565c0',
    messagingSenderId: '478022847809',
    projectId: 'qrparty-6e648',
    storageBucket: 'qrparty-6e648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC6xTEf1TOYA0SqPNDkJvbMdYJqwafrVM',
    appId: '1:478022847809:ios:4bdfd1532463179f3565c0',
    messagingSenderId: '478022847809',
    projectId: 'qrparty-6e648',
    storageBucket: 'qrparty-6e648.firebasestorage.app',
    iosBundleId: 'com.qrparty.app',
  );
}
